server:
  port: 5252
  servlet:
    context-path: /api

spring:
  application:
    2021-spring-toyproject

  http:
    multipart:
      enabled: true
      max-file-size: 10mb

  devtools:
    remote:
      restart:
        enabled: true

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy #logback 설정시 다음과 같이 입력해야 함
    url: jdbc:log4jdbc:postgresql://183.101.136.74:5444/postgres #logback 설정시 앞에 jdbc:log4jdbc 붙여야 함
    username: ENC(OBpS+CdaA8IFDkHuMri4HOKUIG8iAAe3)
    password: ENC(zhN+Fs9PuJhRttA2PdbinNJWIt94Qhva)
    tomcat:
      remove-abandoned: true
      remove-abandoned-timeout: 120
      log-abandoned: true
      max-active: 50
      max-idle: 10
      max-wait: 1000
      #validation-query: "select 1"
      #test-on-borrow: true
      #test-on-connect: true
      test-while-idle: true

  messages:
    basename: classpath:/messages/messages
    encoding: UTF-8

  main:
    web-application-type: servlet

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )

datasource:
  driver-class: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:log4jdbc:postgresql://183.101.136.74:5444/postgres
  username: ENC(OBpS+CdaA8IFDkHuMri4HOKUIG8iAAe3)
  password: ENC(zhN+Fs9PuJhRttA2PdbinNJWIt94Qhva)

author:
  name: TESTER
  age: 53
