server:
  port: 5252
  servlet:
    context-path: /api

spring:
  application:
    2021-spring-toyproject

  http:
    multipart:
      enabled: true
      max-file-size: 10mb

  devtools:
    remote:
      restart:
        enabled: true

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(53SLYc5CWrvHEBmJ8dQMN6YU3CDI9QJQ367jAnoAAatwHY5O901PNUL3qsnGawJ4jyPOCygeCCs=)
    username: ENC(OBpS+CdaA8IFDkHuMri4HOKUIG8iAAe3)
    password: ENC(zhN+Fs9PuJhRttA2PdbinNJWIt94Qhva)
    tomcat:
      remove-abandoned: true
      remove-abandoned-timeout: 120
      log-abandoned: true
      max-active: 50
      max-idle: 10
      max-wait: 1000
      #validation-query: "select 1"
      #test-on-borrow: true
      #test-on-connect: true
      test-while-idle: true


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )



