server:
  port: 5252
  servlet:
    context-path: /api

spring:
  application:
    2021-spring-toyproject

  http:
    multipart:
      enabled: true
      max-file-size: 10mb

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://183.101.136.74:5444/postgres
    username: postgres
    password: ENC(KPEumznakuskZVMbz3hDiF0zIypNLCU5)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )



