server:
  port: 5252
  servlet:
    context-path: /api

spring:
  application:
    2021-spring-toryproject

  http:
    multipart:
      enabled: true
      max-file-size: 10mb

  output:
    ansi:
      enabled: always

  datasource:
    data-username: 